version: '2'

services:
  apache:
    image: 'bitnami/apache:latest'
    ports:
      - '80:8080'
      - '443:8443'
    volumes:
      - ./vhost.conf:/vhosts/kmadigital.conf:ro
      - /etc/ssl/kmacerts:/certs
      - ./www:/app
